services:
  netflixwatcher:
    build: .
    container_name: netflixwatcher
    restart: always

  scheduler:
    image: bash
    container_name: netflixwatcher_scheduler
    restart: unless-stopped
    command: >
      sh -c "while true; do
      sleep $(( $(date -d '18:00:00' +%s) - $(date +%s) ));
      docker restart netflixwatcher;
      sleep 86400;
      done"
