services:
  netflixwatcher:
    build: .
    container_name: netflixwatcher
    restart: always
    env_file:
      - .env
    volumes:
      - type: bind
        source: /var/lib/rpi-observability/netflix-watcher
        target: /metrics

  scheduler:
    image: bash
    container_name: netflixwatcher_scheduler
    restart: unless-stopped
    command: ["bash", "/scheduler.sh"]
    volumes:
      - ./Setup/netflixwatcher_scheduler.sh:/scheduler.sh:ro
      - type: bind
        source: /var/lib/rpi-observability/netflix-watcher
        target: /metrics
