name: Build and Push to Raspberry PI

on:
  push:
    branches: main

env:
  #REGISTRY_NAME: <your-acr-registry>  # replace with your ACR name
  SSH_PORT: 30000
  CONTAINER_NAME: netflixwatcher

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
   
    # Step 2: Set up SSH access
    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PASSWORD }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # Step 3: Copy repo to Raspberry Pi
    - name: Copy Repository to Raspberry Pi
      run: |
        rsync -avz -e "ssh -p ${{ env.SSH_PORT }}" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/home/${{ secrets.SSH_USER }}/netflixWatcher/

    # Step 4: Navigate to the folder and run docker compose
    - name: Run Docker Compose on Raspberry Pi
      run: |
        ssh -p ${{ env.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} << EOF
          cd /home/${{ secrets.SSH_USER }}/netflixWatcher
          docker compose up -d --build
        EOF