name: Build and Push to ACR Windows

on:
  workflow_call

env:
  #REGISTRY_NAME: <your-acr-registry>  # replace with your ACR name
  PORT: 30000
  CONTAINER_NAME: netflixwatcher

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
   

    - name: Connect to Raspberry PI
      uses: invi5H/ssh-action@v1
      with:
        SSH_HOST: ${{ secrets.SSH_SERVER }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_PASSWORD }}
        SSH_PORT: ${{ env.PORT }}

    - name: Copy Files to Raspberry Pi
      run: |
        scp -r . ${{ env.SSH_USER }}@${{ env.SSH_SERVER }}:/home/${{ env.SSH_USER }}/netflixWatcher

    - name: Run netflixWatcher container

      run: |
         cd /home/${{env.SSH_USER}}/netflixWatcher
         docker compose up -d